---
  # Title: Zabbix Agent 3.0.4
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/ubuntu-1604-amd64.yml
  #
  # Description: Monitoring Agent for Zabbix (3.0+)
  #
  # Steps:
  #   - 1. Download & install deb package
  #   - 2. Install zabbix-agent
  #   - 3. Configure Agent

  - name: "1. Download & Install deb package"
    apt:
      deb: http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-2+xenial_all.deb
      state: present

  - name: "2. Install Zabbix-agent"
    apt:
      name: zabbix-agent
      state: present
      update_cache: yes

  - name: "3. Configure Zabbix-agent"
    template:
      src:  zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      backup: yes
    notify:
      - service_restart_zabbix_agent

  - name: "4.1 Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp"
    ufw:
      rule: allow
      port: 10050
      proto: tcp
      from_ip: "{{ zbx_conf_server }}"

  - name: "4.2 Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp"
    ufw:
      rule: allow
      port: 10051
      proto: tcp
      to_ip: "{{ zbx_conf_activeserver }}"
